---
ID: "6366b9c8-81fa-47d6-b143-cf6b32a1f855"
Parent: "cdcd832b-f5ea-4da4-9af6-65bd56c1c81f"
Template: "cdcd832b-f5ea-4da4-9af6-65bd56c1c81f"
Path: /sitecore/templates/Feature/VGW/GlobalComponents/Top Bar Configuration/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{59C8AF87-95BE-44DF-8D4D-BBAF76955AD9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231114T090823Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mihaly.arvai@vgw.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mihaly.arvai@vgw.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "12b60285-f89c-41c5-a829-2be5f8d6b9ae"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mihaly.arvai@vgw.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231114T090830Z
