---
ID: "b3fca115-ca45-4a1a-9bb2-c91ca6e3be8f"
Parent: "978131e2-9e1a-4cdb-93b0-9a596b091a42"
Template: "978131e2-9e1a-4cdb-93b0-9a596b091a42"
Path: "/sitecore/templates/Project/VGW/GlobalPoker/Components/Rendering Parameters/GP-Image-Text/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240208T070307Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JqXVeZpDYv
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JqXVeZpDYv
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "73ebdb38-adce-4eec-ba8b-6e38270126d7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JqXVeZpDYv
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240208T070307Z
