---
ID: "1c644037-e433-481e-9523-3bc48ad686fb"
Parent: "e5b1a163-3fa6-46b1-9a74-36ba4d3ec613"
Template: "e5b1a163-3fa6-46b1-9a74-36ba4d3ec613"
Path: /sitecore/templates/Feature/VGW/Category/Rendering Parameters/ArticleList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231106T104630Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\K891kJYRrD
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\K891kJYRrD
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e6bb2982-dd34-4e2d-8295-566ba435e3ae"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\K891kJYRrD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231106T104630Z
