---
ID: "7c8a08d5-8ed5-4a94-96ab-57ce6bab2fbd"
Parent: "d74e34bd-69a9-4089-9eea-e5d307810502"
Template: "d74e34bd-69a9-4089-9eea-e5d307810502"
Path: /sitecore/templates/Feature/VGW/HomePageComponents/Rendering Parameters/Two Column Articles/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2d1c8068-ec1d-4d5b-91bb-49a6aa02d68c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Mihaly Arvai
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231113T090835Z
