---
ID: "9d3c6187-9e7a-4863-ba28-bc434085289a"
Parent: "c78e42b3-faf3-408e-a62a-aec488b3d35e"
Template: "c78e42b3-faf3-408e-a62a-aec488b3d35e"
Path: /sitecore/templates/Project/VGW/ChumbaCasino/Components/Content Blocks/Rendering Parameters/Three Column Block/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240320T211522Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\iPRIsmIwmb
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\iPRIsmIwmb
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "375d0ddb-2fad-471a-add2-9f64779994d9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\iPRIsmIwmb
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240320T211522Z
