---
ID: "bb9a4dc4-22e8-4731-915c-d38de9249969"
Parent: "d58ce406-0aec-4acf-856b-4978c8bf0ef9"
Template: "d58ce406-0aec-4acf-856b-4978c8bf0ef9"
Path: /sitecore/templates/Feature/VGW/Category/Rendering Parameters/CategoryPageHeading/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d0e1c7a9-9180-4af3-b607-bf3ba8b3c2cf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\K891kJYRrD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231106T103957Z
