---
ID: "3195ab21-b61e-439c-be96-b6611b097b42"
Parent: "8cf80ce6-c705-41cb-b782-869b513918c3"
Template: "8cf80ce6-c705-41cb-b782-869b513918c3"
Path: /sitecore/templates/Feature/VGW/HomePageComponents/Rendering Parameters/Dual Articles/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5ed3bdad-8c22-41b6-997c-7abb6957ec66"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Mihaly Arvai
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231115T112209Z
