---
ID: "44f923fa-e742-4c12-844a-9e5b4f4d7e88"
Parent: "aa87aa44-902b-43ed-b732-659a7f9be54b"
Template: "aa87aa44-902b-43ed-b732-659a7f9be54b"
Path: /sitecore/templates/Feature/VGW/HomePageComponents/Rendering Parameters/Three Column Articles/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "41c51677-2d73-426c-ace4-748b161fbfc9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mihaly.arvai@vgw.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231110T075836Z
