---
ID: "d4c2d31f-f906-463c-a561-bc89276c2f99"
Parent: "c3347464-40a8-423b-aec3-b032898840f7"
Template: "c3347464-40a8-423b-aec3-b032898840f7"
Path: /sitecore/templates/Feature/VGW/Article/Rendering Parameters/Quote/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "26eb99ae-f920-4e51-8a90-d756ed0f7d36"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231031T092208Z
