---
ID: "d6cd34a3-fc03-42bd-ab1c-84e508bb390f"
Parent: "7eb4abc2-39af-4df8-b1ac-3bc6e1ed9637"
Template: "7eb4abc2-39af-4df8-b1ac-3bc6e1ed9637"
Path: /sitecore/templates/Feature/VGW/Page Content/Rendering Parameters/ImageText/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1b97c76b-0cb3-4140-80b6-65666bf4127c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231031T091053Z
