---
ID: "1c0a9991-01c0-436d-b2b9-ecc3e815ea39"
Parent: "66e52705-6638-4bf7-bb25-ad0481b9619c"
Template: "66e52705-6638-4bf7-bb25-ad0481b9619c"
Path: /sitecore/templates/Project/VGW/ChumbaCasino/Components/CCBanner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240321T200833Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\iPRIsmIwmb
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\iPRIsmIwmb
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "54be0fb0-0fae-4eb4-8b62-e0106f05fba4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\iPRIsmIwmb
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240321T200833Z
