---
ID: "725a6953-8d1f-41d8-8e3f-9ce762139bd6"
Parent: "67c7ae03-c9d9-469b-aa9a-1f5c47e8bf16"
Template: "67c7ae03-c9d9-469b-aa9a-1f5c47e8bf16"
Path: /sitecore/templates/Feature/VGW/GlobalComponents/Rendering Parameters/SiteNavigation/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9fc8ede6-650e-4e41-9514-b6dc5792f5d0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231026T072047Z
