---
ID: "732da5e2-23f7-419b-937f-15ff9a8668e1"
Parent: "87c17ffd-549c-4c7a-a147-7e5d74c3165c"
Template: "87c17ffd-549c-4c7a-a147-7e5d74c3165c"
Path: /sitecore/templates/Feature/VGW/Article/Rendering Parameters/ArticlesByTag/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f9aab6bb-d94d-4007-a477-e680629c0eb4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\K891kJYRrD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231102T132238Z
