---
ID: "5d9d0f80-f990-41ed-8552-ac9db7503977"
Parent: "82e6f461-6a12-43ab-b2c8-f9b975eda5d7"
Template: "82e6f461-6a12-43ab-b2c8-f9b975eda5d7"
Path: "/sitecore/templates/Project/VGW/GlobalPoker/Components/Rendering Parameters/Banner-Full/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240130T022439Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JqXVeZpDYv
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JqXVeZpDYv
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e3d06bc3-44c2-4e6f-91ac-9e5b07c3f04b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JqXVeZpDYv
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240130T022439Z
