---
ID: "bf464793-bdf1-40c3-a5ca-60c88163fa0a"
Parent: "e62ec61e-42d4-4217-a39c-c66f28521bfe"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/VGW/GlobalPokerAcademy/Presentation/Headless Variants/Article List/Default
BranchID: "d4fdc5b4-b568-4540-b929-3a8b49a51d2c"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{108977FC-2D28-46C9-A989-DE75E226DBD9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231024T093755Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4c73dd5f-2080-4ffa-8d4f-b44b5870e450"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231024T093755Z
