---
ID: "af1ea88b-c32e-4a58-9413-0c6f906860e5"
Parent: "d6ef407c-caaf-4d65-9936-044b4c7c102e"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/VGW/GlobalPokerAcademy/Presentation/Headless Variants/ImageText/Default
BranchID: "90881e3f-35d4-43f3-bf07-65cacf1cc83c"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{1928BD85-1C3D-4091-8A10-F4BF575D7995}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231031T091302Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "290ccd9d-6624-4bf4-b6d2-0f8249b5cf67"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231031T091302Z
