---
ID: "55744699-c500-429a-914d-d65dc2fb30e3"
Parent: "6f17f602-83da-4ea8-b5ff-b40ee43a9456"
Template: "6f17f602-83da-4ea8-b5ff-b40ee43a9456"
Path: /sitecore/templates/Project/VGW/GlobalPoker/Components/Rendering Parameters/CardGrid/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240226T051311Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JqXVeZpDYv
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JqXVeZpDYv
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5f7addde-eafd-4f6d-82ca-40848d121db2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JqXVeZpDYv
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240228T232912Z
