---
ID: "ce9dacb5-46cd-4aa6-88fe-9e106b4e5c69"
Parent: "c80d4ca2-8c63-44fe-9064-9d87287ea427"
Template: "c80d4ca2-8c63-44fe-9064-9d87287ea427"
Path: /sitecore/templates/Feature/VGW/HomePageComponents/Rendering Parameters/Article Top Picks/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e980c35b-ae33-49d9-8847-ff1ba16a70bf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\K891kJYRrD
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231108T115527Z
