---
ID: "5858b2ab-15cb-46c8-b306-dc5ee4053e27"
Parent: "7d15c46c-26cb-4ff7-9770-1981e8876427"
Template: "3b2a81dd-e9a9-44d5-b8ed-e20e233deceb"
Path: /sitecore/content/VGW/GlobalPokerAcademy/Settings/Footer Configuration
SharedFields:
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\Global Poker Academy Author|pd|+item:delete|+item:write|+item:rename|+item:create|pe|+item:delete|+item:write|+item:rename|+item:create|
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231026T104207Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mihaly_arvai@epam.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "50628bd6-e114-408d-8e7c-99c24e47d5ba"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mihaly.arvai@vgw.co
    - ID: "cbe5e723-dc4f-4ca2-a7f2-90a98c4b615e"
      Hint: Logo
      Value: |
        <image mediaid="{F06DC8F3-83E0-40DC-B065-E80C99A674D2}" />
    - ID: "d375f74b-9ab6-46fc-b2d7-20b9ae9f41bc"
      Hint: Copyright Text
      Value: ©VGW Group 2012. All rights reserved. NO PURCHASE NECESSARY to enter Sweepstakes.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231114T085659Z
